### ISSUE TITLE
Support multiple book formats (Part 1 done; Part 2 split to #1390)

### ISSUE THREAD

**Issue by stephaniewilkinson** [stephaniewilkinson/yonderbook#542]
Original idea (2019): https://twitter.com/stephanieblack/status/1177327368764919808

Absorbs #442 ("expand this section to include links and ids for other book formats"), which was the implementation detail of part 1.

---

## Part 1 — Book formats

Support finding physical and audiobook copies at the library, not just ebooks.

### There is no format-safety anywhere in the pipeline

The OverDrive product search sends no format filter — `availability_path` (`lib/overdrive.rb:172-176`) queries `minimum: false, limit: 5, q: <isbn or "title">`.

For a book **with** an ISBN, `try_title_search_with_metadata` short-circuits on the first line:

```ruby
return isbn_search_body unless no_products?(isbn_search_body)   # lib/overdrive.rb:310
```

— returning the raw body with **every** product the search matched, up to 5, with no filtering. `expand_editions` (`:214-228`) then turns each one into a `Title` carrying the *original Goodreads* ISBN (`isbn: book.isbn`, `:220`) rather than the edition's own identifier, so `consolidate_duplicate_titles` (`:264`) groups them all under one key and keeps whichever has the highest `copies_available` (`should_replace?`, `:152`).

`mediaType` is never read anywhere in the file, and `views/availability.erb:35,53` label every result "Read" / "Reserve" unconditionally.

**Net effect: if that search returns more than one format for a title, the one with the most copies wins and is presented as an ebook regardless of what it is.**

### Needs verifying

Whether an ISBN keyword query actually returns audiobook products alongside the ebook. An ISBN is edition-specific, but `q` is a general keyword search, not an exact-field match. If OverDrive reliably returns exactly one product per ISBN, the collision is latent rather than live.

Requires OverDrive API credentials to check. **Do this first** — it determines whether Part 1 is a bug fix or a feature.

The no-ISBN path is unaffected either way: `validate_title_search_results` (`:298`) narrows to a single matched product.

### Scope

- Add a format field to `Overdrive::Title` (`lib/overdrive.rb:49`), populated from the product's `mediaType`
- Key `consolidate_duplicate_titles` on `[identifier, format]` rather than identifier alone
- Surface format in the UI — filter or per-result badge — so the action label is accurate
- Decide whether physical copies are in scope; OverDrive is digital-only, so that needs a different data source

### Related cleanup

`availability_url` on `Overdrive::Title` is dead: declared at `lib/overdrive.rb:49`, set to `nil` at lines 166 and 225, read nowhere. Either populate it as part of this work or delete the field.

## Part 2 — Multiple library systems

Let a user check more than one consortium at once (e.g. NYPL + Brooklyn PL).

`Overdrive#initialize` takes a single `consortium_id` and resolves one `@collection_token` (`lib/overdrive.rb:63-99`), and the token is cached per session as a scalar (`app.rb:262`). Supporting N libraries means fanning out per consortium and merging results, plus a UI decision about how to show "available at Brooklyn, waitlist at NYPL" for one book.

Larger than Part 1 and independent of it — reasonable to split back out once Part 1 lands.

## Acceptance criteria

**Part 1**
- [ ] Confirmed whether multi-format results actually occur for ISBN searches
- [ ] Format captured on `Title` from `mediaType`
- [ ] Consolidation no longer collapses across formats
- [ ] UI action label matches the actual format
- [ ] `availability_url` populated or removed

**Part 2**
- [ ] Multiple consortia selectable
- [ ] Results merged with per-library availability visible

**Comment by stephaniewilkinson** [comment]
Part 1 is done in #1391: `Title` carries the product's `mediaType`, consolidation keys on `[identifier, format]` so formats no longer collapse into one row, each result badges its format, an audiobook says "Listen", and the dead `availability_url` field is gone.

Part 2, multiple library systems, is split out to #1390 — which this issue proposed itself: "Larger than Part 1 and independent of it — reasonable to split back out once Part 1 lands." The open question about physical copies went with it, since OverDrive is digital-only and that needs a different data source.

One acceptance criterion is unmet and stays unmet: whether an ISBN keyword query actually returns more than one format. That needs live OverDrive credentials. It does not change what the code should do — either the collision happens and #1391 fixes a live defect, or it does not yet and the search is one format filter away from producing it, with the labels wrong either way. The multi-format case is pinned by a spec against a stubbed two-product response. If you run the check with real credentials, the answer is worth recording on #1390.

**Comment by stephaniewilkinson** [comment]
The open acceptance criterion here — "confirmed whether multi-format results actually occur for ISBN searches" — is now answered. Measured against live OverDrive on 2026-09-18, Seattle Public Library.

**For ISBN searches: no, because ISBN searches return nothing at all.** Seven queries returned zero products, including one using a digital ISBN lifted straight off an OverDrive product. The `q=` parameter does not index ISBNs. Filed as #1394, because it also means every book pays for two searches where one would do — against the phase the README calls the main bottleneck.

**For the title search that actually runs: yes, emphatically.** It returns both formats mixed (4 audiobook, 6 ebook in a 10-result page), and `find_matching_product_via_metadata` takes the first author+title match with no format preference. OverDrive returns audiobooks first, so five of five books tested resolved to the audiobook. Filed as #1395.

So #1391 was a **live** fix rather than the latent one it was filed as. The consolidation collapse it guarded against cannot currently happen — the title fallback returns a single product — but the mislabelling was near-total: every one of those books was shown as an ebook with a "Read" button pointing at an audiobook.

Nothing to reopen here. Both follow-ups are filed, and #1395 is now cheap because #1390 built the one-row-per-book-with-copies model it needs.
